name: Python application test

on:
  push:
    branches:
      - homework
  pull_request:
    branches:
      - homework

jobs:
  test_api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12.1' ]

    steps:
      - name: Checkout to homework branch
        uses: actions/checkout@v4
        with:
          ref: homework

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: "slawekradzyminski/awesome-localstack"
          path: "awesome-localstack"
      - name: Run Docker Compose
        run: |
          cd awesome-localstack
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh

      - name: Installing all necessary packages
        run: pip install -r requirements.txt

      - name: API tests
        env:
          ADMIN_USERNAME: "admin"
          ADMIN_PASSWORD: "admin"
          BACKEND_URL: "http://localhost:4001"
        run: pytest -v tests/api/
